/** Campos do SingletonEditor para o tema Curso de Ar Condicionado�e (home). */

export const cursodear_HOME_FIELDS = [
    { key: 'heroKicker', type: 'text', label: 'Selo acima do título (hero)' },
    { key: 'heroTitle', type: 'text', label: 'Título principal' },
    { key: 'heroSubtitle', type: 'text', label: 'Subtítulo', multiline: true, rows: 3 },
    {
        key: 'metaTitle',
        type: 'text',
        label: 'SEO — título da página (tag <title>; diferente do título do hero)',
    },
    {
        key: 'metaDescription',
        type: 'text',
        label: 'SEO — meta description (Google)',
        multiline: true,
        rows: 3,
    },
    { key: 'heroBgImage', type: 'text', label: 'URL da imagem de fundo (hero)' },
    { key: 'heroCtaPrimaryText', type: 'text', label: 'Texto botão principal' },
    { key: 'heroCtaPrimaryHref', type: 'text', label: 'Link botão principal' },
    { key: 'heroCtaSecondaryText', type: 'text', label: 'Texto botão secundário' },
    { key: 'heroCtaSecondaryHref', type: 'text', label: 'Link botão secundário' },
    { key: 'aboutTitle', type: 'text', label: 'Sobre nós — título' },
    { key: 'aboutText', type: 'text', label: 'Sobre nós — texto', multiline: true, rows: 6 },
    { key: 'aboutImage', type: 'text', label: 'Sobre nós — URL da foto (lado direito). Vazio = imagem padrão' },
    { key: 'aboutCtaText', type: 'text', label: 'Sobre nós — texto do botão' },
    { key: 'aboutCtaHref', type: 'text', label: 'Sobre nós — link do botão' },
    { key: 'categoriesSectionTitle', type: 'text', label: 'Título da seção de categorias' },
    {
        key: 'categoryCards',
        type: 'array',
        label: 'Cards (categorias / destaques)',
        itemLabel: () => 'Card',
        defaultItem: { href: '/blog', icon: '✨', title: '', description: '' },
        fields: [
            { key: 'href', type: 'text', label: 'Link' },
            { key: 'icon', type: 'text', label: 'Ícone (emoji)' },
            { key: 'title', type: 'text', label: 'Título' },
            { key: 'description', type: 'text', label: 'Descrição', multiline: true, rows: 2 },
        ],
    },
    { key: 'latestPostsTitle', type: 'text', label: 'Título “Últimos artigos”' },
    { key: 'latestPostsCtaText', type: 'text', label: 'Texto do botão ver todos' },
    { key: 'emptyLatestText', type: 'text', label: 'Mensagem sem posts' },
    { key: 'newsletterTitle', type: 'text', label: 'Newsletter — título' },
    { key: 'newsletterDescription', type: 'text', label: 'Newsletter — descrição', multiline: true, rows: 2 },
    { key: 'newsletterPlaceholder', type: 'text', label: 'Newsletter — placeholder do e-mail' },
    { key: 'newsletterButtonText', type: 'text', label: 'Newsletter — texto do botão' },
    {
        key: 'showLatestPostsOnHome',
        type: 'select',
        label: 'Mostrar grade de artigos na home',
        defaultValue: 'sim',
        options: [
            { value: 'sim', label: 'Sim (blog na home)' },
            { value: 'nao', label: 'Não (landing focada em venda)' },
        ],
    },
    {
        key: 'showNewsletterOnHome',
        type: 'select',
        label: 'Mostrar bloco de newsletter no final',
        defaultValue: 'sim',
        options: [
            { value: 'sim', label: 'Sim' },
            { value: 'nao', label: 'Não' },
        ],
    },
    {
        key: 'categoriesSectionSubtitle',
        type: 'text',
        label: 'Subtítulo abaixo do título da seção de cards (opcional)',
        multiline: true,
        rows: 2,
        description: 'Se vazio, usamos um texto padrão. Em landing, descreva os 3 pilares do curso.',
    },
    { key: 'landingOfferBadge', type: 'text', label: 'Landing — selo da oferta (ex.: Acesso imediato)' },
    { key: 'landingOfferTitle', type: 'text', label: 'Landing — título da caixa de preço/oferta' },
    {
        key: 'landingOfferSubtitle',
        type: 'text',
        label: 'Landing — texto abaixo do título da oferta',
        multiline: true,
        rows: 2,
    },
    { key: 'landingPriceLine', type: 'text', label: 'Landing — linha de preço (ex.: 12x de R$ 39,90 ou à vista R$ 397)' },
    {
        key: 'landingOfferNote',
        type: 'text',
        label: 'Landing — observação (parcelamento, garantia, etc.)',
        multiline: true,
        rows: 2,
    },
    { key: 'landingOfferCtaText', type: 'text', label: 'Landing — texto botão principal da oferta' },
    {
        key: 'landingOfferCtaHref',
        type: 'text',
        label: 'Landing — link do botão (WhatsApp, checkout, /contato)',
        placeholder: 'https://wa.me/5511999999999',
    },
    {
        key: 'landingIncludedTitle',
        type: 'text',
        label: 'Landing — título “O que está incluso”',
    },
    {
        key: 'landingIncludedItems',
        type: 'array',
        label: 'Landing — itens inclusos no curso',
        itemLabel: (item: { title?: string }) => item?.title || 'Item',
        defaultItem: { icon: '✓', title: '', text: '' },
        fields: [
            { key: 'icon', type: 'text', label: 'Ícone (emoji)' },
            { key: 'title', type: 'text', label: 'Título' },
            { key: 'text', type: 'text', label: 'Descrição', multiline: true, rows: 2 },
        ],
    },
    {
        key: 'landingModulesTitle',
        type: 'text',
        label: 'Landing — título do programa/módulos',
    },
    {
        key: 'landingModules',
        type: 'array',
        label: 'Landing — módulos do curso',
        itemLabel: (item: { title?: string }) => item?.title || 'Módulo',
        defaultItem: { title: '', text: '' },
        fields: [
            { key: 'title', type: 'text', label: 'Nome do módulo' },
            { key: 'text', type: 'text', label: 'Conteúdo', multiline: true, rows: 3 },
        ],
    },
    {
        key: 'landingFaqTitle',
        type: 'text',
        label: 'Landing — título FAQ',
    },
    {
        key: 'landingFaq',
        type: 'array',
        label: 'Landing — perguntas e respostas',
        itemLabel: (item: { q?: string }) => item?.q || 'Pergunta',
        defaultItem: { q: '', a: '' },
        fields: [
            { key: 'q', type: 'text', label: 'Pergunta' },
            { key: 'a', type: 'text', label: 'Resposta', multiline: true, rows: 3 },
        ],
    },
    { key: 'landingClosingTitle', type: 'text', label: 'Landing — faixa final — título' },
    {
        key: 'landingClosingText',
        type: 'text',
        label: 'Landing — faixa final — texto',
        multiline: true,
        rows: 2,
    },
    { key: 'landingClosingCtaText', type: 'text', label: 'Landing — faixa final — texto do botão' },
    { key: 'landingClosingCtaHref', type: 'text', label: 'Landing — faixa final — link do botão' },
];

export const cursodear_ABOUT_FIELDS = [
    { key: 'heroTitle', type: 'text', label: 'Título' },
    { key: 'heroSubtitle', type: 'text', label: 'Subtítulo', multiline: true, rows: 2 },
    { key: 'heroImage', type: 'text', label: 'URL da imagem (opcional)' },
    { key: 'body', type: 'text', label: 'Texto principal', multiline: true, rows: 8 },
    { key: 'ctaLinkText', type: 'text', label: 'Texto do link final' },
    { key: 'ctaLinkHref', type: 'text', label: 'URL do link final' },
    {
        key: 'teamMembers',
        type: 'array',
        label: 'Equipe',
        itemLabel: (item: { name?: string }) => item?.name || 'Pessoa',
        defaultItem: { name: '', role: '', bio: '', emoji: '👤', photo: '' },
        fields: [
            { key: 'name', type: 'text', label: 'Nome' },
            { key: 'role', type: 'text', label: 'Função' },
            { key: 'bio', type: 'text', label: 'Bio', multiline: true, rows: 2 },
            {
                key: 'photo',
                type: 'text',
                label: 'URL da foto (ex. /authors/nome.png). Se preenchido, substitui o emoji no site',
            },
            { key: 'emoji', type: 'text', label: 'Emoji (só aparece se a foto estiver vazia)' },
        ],
    },
];
